### ISSUE TITLE
SyntaxError: mdsvex does not provide an export named mdsvex

### ISSUE THREAD

**Issue by sonya-ninja** [svelte-add/mdsvex#11] opened 2021-05-08 16:36 UTC
Sorry - I'm a newbie so hope I'm giving some helpful info.

Brand new sveltekit install:

- Skeleton Project
- No Typescript
- No ES Lint
- No Prettier
- pnpm install
- npx svelte-add mdsvex
- pnpm install
- npm run dev -- --port 4010

Everything seems to be working fine with no errors.

In index.svelte:
```
<script>
    import Example from '$lib/Example.svelte.md'
</script>

<Example />
```

Visual studio immediately displays an error:

> Error in svelte.config.js
> SyntaxError: The requested module 'mdsvex' does not provide an export named 'mdsvex'

The page at http://localhost:4010/ seems to be displaying perfectly however.

Can I carry on with my project? Will this error cause unexpected breaking of Svelte-kit?

**Comment by babichjacob** [comment] 2021-05-08 16:40
Upgrade to the newest versions of Node (16.1.0 or 14.16.1) and especially the newest version of VS Code. They *just* fixed this.

**Comment by sonya-ninja** [comment] 2021-05-08 16:50
Thanks @babichjacob !

- Visual Studio says "There are currently no updates available"
- node --version says v16.1.0

And just for good-measure I did "pnpm up" and restarted VS Code.

I still get the error in the VS Problems tab.

Could I be doing something else wrong?

**Comment by babichjacob** [comment] 2021-05-08 16:53
I'm not sure. I'm not home so I'll have to check if I can reproduce this later. A repository and more exact information about `node -v` and `code -v` (might be the right syntax?) would be helpful but might not end up being necessary — I don't know.

**Comment by sonya-ninja** [comment] 2021-05-08 16:57
Here is my repository - https://github.com/sonya-ninja/Svelte-Kitten

node -v says v16.1.0
code Version: 1.56.0

Thank you! Let me know if you need anything else.

**Comment by vhollo** [comment] 2021-05-08 19:53
With Netlify deploy an environment variable must be set until they update Node.

**Comment by babichjacob** [comment] 2021-05-08 19:57
> Visual studio immediately displays an error:
> 
> > Error in svelte.config.js
> > SyntaxError: The requested module 'mdsvex' does not provide an export named 'mdsvex'

Wait, is this Visual Studio or VS Code?

**Comment by sonya-ninja** [comment] 2021-05-08 20:15
@babichjacob 

Visual Studio Code

**Comment by vhollo** [comment] 2021-05-08 20:50
Look, my VSCodium keeps a different version than my Terminal. May be the case at you?
![Screenshot 2021-05-08 at 22 45 43](https://user-images.githubusercontent.com/359659/117553099-bfb2c080-b04f-11eb-8442-8314ad6cb503.png)

> Here is my repository - https://github.com/sonya-ninja/Svelte-Kitten
> 
> node -v says v16.1.0
> code Version: 1.56.0
> 
> Thank you! Let me know if you need anything else.

**Comment by babichjacob** [comment] 2021-05-08 20:52
> Look, my VSCodium keeps a different version than my Terminal. May be the case at you?
> ![Screenshot 2021-05-08 at 22 45 43](https://user-images.githubusercontent.com/359659/117553099-bfb2c080-b04f-11eb-8442-8314ad6cb503.png)
> 
> > Here is my repository - https://github.com/sonya-ninja/Svelte-Kitten
> > node -v says v16.1.0
> > code Version: 1.56.0
> > Thank you! Let me know if you need anything else.

VS Codium needs to update to match VS Code then:

![image](https://user-images.githubusercontent.com/22732095/117553138-c45e8100-b01d-11eb-8434-59aedbdd3096.png)

Closing as not an issue with this project.

**Closed by babichjacob** 2021-05-08 20:52 UTC
Labels: bug

**Comment by vhollo** [comment] 2021-05-08 21:23
Forked your repo, @sonya-ninja.
Local build is fine with NodeJS v15.3.0.
Netlify build fails like yours, unless I add to netlify.toml in the root:
[context.production]
  environment = { NODE_VERSION = "15.3.0" }

Try to update Node on whatever platform you build.

**Comment by sonya-ninja** [comment] 2021-05-09 04:47
@vhollo Thank you so much for the help. After reading your post I checked - my node version for VSCode is different to the nvm default version on my mac. I will try and get VSCode and NVM to use the same default today. I've tried with a launch file and with nvm use default. Nothing has worked yet. When you're a beginner, your system can get really messy - too much copying and pasting terminal commands from tutorials without truly understanding what I'm doing. :)

 I'm also SO grateful for your advice on the production build toml file. I hadn't tried deploying this project yet, so I'm sure that will save me many hours of frustration!

**Comment by babichjacob** [comment] 2021-05-09 04:50
> I will try and get VSCode and NVM to use the same default today. 

I don't think they can (or that trying to force it to be the case is a good idea). VS Code is updated with support to solve this issue (hence why SvelteKit and all has just moved to ESM configs), so I don't believe there is a need either. Waiting patiently for VS Codium to update over the next few days seems like the best option to me, since these are just IDE warnings and not errors preventing app building and deployment.

**Comment by babichjacob** [comment] 2021-05-09 05:29
> Can I then safely assume that anything I code that doesn't work is _MY_ fault and not because of that IDE warning?

Hmm, I'd say you can't assume that and can only find that out with research and testing. If it's at least somewhat related to this project, you can ask about it here (preferably in this issue we are currently in rather than a new one unless a new bug is found).
